### ISSUE TITLE
[Toward Cloud-Migrator platform v0.3.0] Proto/draft API docs, simple/sample guides 

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cloud-migrator#13]
API-First 접근법을 바탕으로 Cloud-Migrator platform v0.3.0 릴리스를 추진 중에 있습니다 🚀 
: Ref https://github.com/cloud-barista/cloud-migrator/issues/11

**Proto/draft API 및 docs, simple/sample guides 에 대한 현황 파악 및 공유가 필요해 보여 별도의 Issue를 오픈 하였습니다.** 

다음 3가지 사항에 대해 추진 및 협조를 부탁 드립니다.
☑ 1. Proto/draft API 개발 및 Docs 작성
☑ 2. API 활용을 위한 Simple/sample guide 작성
☑ 3. Pre-release 및 공유 

😉 이슈가 있으시면 편하게 공유해주시기 바라며, 
📅 기한은 9/11(수)까지 추진해 보겠습니다. 

**Simple/sample guides 작성하실 때 참고하시기 바랍니다.**
> [!NOTE]
> 가능한 간결하게 작성
> 자유 양식
> API들을 활용하기 위한 순서
> 예상되는 변경 사항 표시 (API 사용자에게 알려야 할 사항)

### CM-Butterfly
@dogfootman @MZC-CSC (cc. @innodreamer)
* Repository: https://github.com/cloud-barista/cm-butterfly
* API documentation: N/A
* Simple/sample guide: N/A <- need to doublecheck if it's necessary

### CM-Mayfly
@dev4unet @MZC-CSC (cc. @innodreamer)
* Repository: https://github.com/cloud-barista/cm-mayfly
* API documentation: N/A
* Simple/sample guide: N/A <- need to double-check if it's necessary

### CM-Ant
@hippo-an (cc. @seokho-son)
* Repository: https://github.com/cloud-barista/cm-ant
* API documentation: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cm-ant/main/api/swagger.yaml
* [x] Simple/sample guide: https://github.com/cloud-barista/cm-ant/wiki/CM%E2%80%90ANT-Simple--&-Sample-API-Usage-guide

### CM-Cicada
@ish-hcc (cc. @sykim-etri)
* Repository: https://github.com/cloud-barista/cm-cicada
* API documentation: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cm-cicada/main/pkg/api/rest/docs/swagger.yaml
* [x] Simple/sample guide: https://github.com/cloud-barista/cm-cicada/blob/main/README.md

### CM-Damselfly
@innodreamer
* Repository: https://github.com/cloud-barista/cm-damselfly
* [x] API documentation: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cm-damselfly/refs/heads/main/api/swagger.yaml
* [x] Simple/sample guide: https://github.com/cloud-barista/cm-damselfly/discussions/25

### CM-Grasshopper
@ish-hcc (cc. @sykim-etri)
* Repository: https://github.com/cloud-barista/cm-grasshopper
* API documentation: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cm-grasshopper/main/pkg/api/rest/docs/swagger.yaml
* [x] Simple/sample guide: https://github.com/cloud-barista/cm-grasshopper

### CM-Beetle
@yunkon-kim @seokho-son @sykim-etri 
* Repository: https://github.com/cloud-barista/cm-beetle
* API documentation: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cm-beetle/main/api/swagger.yaml
* [x] Simple/sample guide: https://github.com/cloud-barista/cm-beetle/discussions/105

### CM-Honeybee
@ish-hcc (cc. @powerkimhub)
* Repository: https://github.com/cloud-barista/cm-honeybee
* API documentation:
  - Agent: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cm-honeybee/main/agent/pkg/api/rest/docs/swagger.yaml
  - Server: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cm-honeybee/main/server/pkg/api/rest/docs/swagger.yaml
* [x] Simple/sample guide: https://github.com/cloud-barista/cm-honeybee/blob/main/README.md
### CB-Tumblebug
@seokho-son @sykim-etri @yunkon-kim
* Repository: https://github.com/cloud-barista/cb-tumblebug
* API documentation: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/main/src/api/rest/docs/swagger.yaml
* [x] Simple/sample guide: https://github.com/cloud-barista/cb-tumblebug/discussions/1731

### CB-Spider
@powerkimhub 
* Repository: https://github.com/cloud-barista/cb-spider
* API documentation: https://cloud-barista.github.io/api?url=https://raw.githubusercontent.com/cloud-barista/cb-spider/master/api/swagger.yaml
* [x] Simple/sample guide: [Simple-Sample-API-Guide](https://github.com/cloud-barista/cb-spider/wiki/Simple-Sample-API-Guide)

### mc-data-manager
N/A (cc. @yunkon-kim)
* Repository: https://github.com/cloud-barista/mc-data-manager
* API documentation: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/mc-data-manager/main/websrc/docs/swagger.yaml
* [x] Simple/sample guide: https://github.com/cloud-barista/mc-data-manager

### cm-model
* Repository (under-experimental): https://github.com/cloud-barista/cm-model
* [x] Simple/sample guide: https://github.com/cloud-barista/cm-model

**Comment by yunkon-kim** [comment]
(Beetle) 9/9(월)까지 pre-release 후, 공유 드릴 수 있을 것 같습니다.

**Comment by powerkimhub** [comment]
@yunkon-kim 

<br>

**[CB-Spider]**
- API documentation: link를 다음으로 교체 부탁 드립니다. 
  - https://cloud-barista.github.io/api?url=https://raw.githubusercontent.com/cloud-barista/cb-spider/master/api/swagger.yaml

- Simple-Sample-API-Guide는 다음과 같습니다.
  - [Simple-Sample-API-Guide](https://github.com/cloud-barista/cb-spider/wiki/Simple-Sample-API-Guide)

**Comment by yunkon-kim** [comment]
[Beetle]
v0.2.1 pre-release: https://github.com/cloud-barista/cm-beetle/releases/tag/v0.2.1
Simple/sample guide: https://github.com/cloud-barista/cm-beetle/discussions/105

**Comment by yunkon-kim** [comment]
@powerkimhub @seokho-son @sykim-etri @yunkon-kim @innodreamer @ish-hcc @hippo-an @dev4unet @MZC-CSC @dogfootman @dongjae 

안녕하세요.

오늘까지 Proto/draft API docs, simple/sample guides 공유를 목표로 하고 있습니다. 
: 잠적정인 목표 일정이었기에 추진과 관련하여 이슈가 있으신지 문의를 드립니다.
: **이슈가 있으신 경우 현황 공유차원에서 답글을 남겨주시면 좋을 것 같습니다.**

아울러, 아래 사항도 함께 살펴봐 주시기 바랍니다.
* Port Numbers: https://github.com/cloud-barista/cloud-migrator/discussions/12
* Cloud-Migrator v0.3.0 시나리오 공유 문서(Live): https://docs.google.com/spreadsheets/d/1gkw6hW3g8eJmuYWuzog8Fz7SERcecWS_/edit?gid=303753738#gid=303753738

**Comment by dev4unet** [comment]
@yunkon-kim 저희쪽 이슈는 공개 보다는 상황 파악에 대한 이슈로 일주일 전에 slack에 문의 남겨 놓은 내용입니다만...
https://github.com/cloud-barista/cloud-migrator/issues/11 의 통합 주요 기능 및 관계도 흐름 기반으로 이해하기로는 Honeybee에서 입력 모델 정보를 리턴해야 하는 것 같은데 지금까지 공개된  Honeybee의 api를 살펴 봐도 Infra의 **RAW 데이터를 리턴**하는 API는 있지만 **저희쪽에서 필요한 RAW가 아닌 모델을 조회하는 AP가 없습니다.**

Beetle은 정제된 모델을 입력으로 전달 받기 때문에 정제된 모델 정보가 필요한데 모델 정보 관련 부분을 참고할 내용들이 없어서 오늘 마감 예정인 가이드 문서에서 관련 내용을 확인할 수 있었으면 합니다.

1)
Honeybee에서 모델 데이터를 리턴하나요?
아니면 Damselfly에서 RAW를 입력으로 전달 받아서 데이터 모델로 변환하나요?

2)
Damselfly는 Honeybee / Beetle / Grasshopper에서 최초 리턴하는 소스/목표 모델과 수정된 소스/목표 사용자 모델 둘 다 취급하나요? 아니면 사용자 모델만 취급하나요?

모델과 관련된 부분에 대해서 어떤 순서로 어떤 프레임워크의 어떤 api들을 이용해서 진행해야 하는지가 파악되면 좋을 것 같습니다.

**Comment by yunkon-kim** [comment]
@dev4unet 현황 공유 감사합니다.

1과 관련하여 말씀드립니다.

Beetle에서 인프라 모델(on-premise model)과 관련한 테스트 후, release 한 터라 관련 사항이 조금 지체 되었습니다. 이점에 대해 양해를 구합니다. 
 
Honeybee에서 인프라 모델을 리턴하는 API 추가를 부탁드려놓은 상태로, 자세한 사항은 다음 이슈를 참고하시면 될 것 같습니다. 
: https://github.com/cloud-barista/cm-honeybee/issues/35 

@innodreamer (cc. @powerkimhub @dongjae) 2번에 대해 추진 계획/의견 부탁드립니다.

**Comment by hippo-an** [comment]
@yunkon-kim 


cm-ant 의 simple and sample api 호출 가이드 링크입니다.

https://github.com/cloud-barista/cm-ant/wiki/CM%E2%80%90ANT-Simple--&-Sample-API-Usage-guide

**Comment by ish-hcc** [comment]
@yunkon-kim 
cm-honeybee, cm-cicada Simple 가이드 입니다.
cm-grasshopper 는 좀 더 개선 후 공유 드리도록 하겠습니다

cm-honeybee: https://github.com/cloud-barista/cm-honeybee/blob/main/README.md
cm-cicada: https://github.com/cloud-barista/cm-cicada/blob/main/README.md

**Comment by innodreamer** [comment]
@yunkon-kim 
상단의 게시 글에 아래의 Damselfly API, Sample guide link 반영 부탁드립니다.
- API documentation: https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cm-damselfly/refs/heads/main/api/swagger.yaml
- Simple/sample guide: https://github.com/cloud-barista/cm-damselfly/discussions/25

**Comment by yunkon-kim** [comment]
Resolved
