### ISSUE TITLE
Sequence Diagram flow check for CM-Butterfly

### ISSUE THREAD

**Issue by hippo-an** [cloud-barista/cloud-migrator#16]
안녕하세요.

cloud-migrator 의 시퀀스 다이어그램과 관련하여, [시퀀스 다이어그램](https://github.com/cloud-barista/cloud-migrator/blob/22556593dcc14382c7cf31f33b2495a0e738814b/docs/sequence-diagrams-for-user-scenarios.md) 기준으로 CM-Butterfly (v0.3.0) 표현되어 있지 않은 부분에 대해서 전달드립니다.

- Retrieve the information of source computing environment (raw data, shape information)
  - 별도의 조회 api 호출 없이 honeybee 의 extract API 요청 결과값 사용
    - source computing environment 의 정보를 수집(POST /source_group/{sgId}/import/infra) 하고 해당 정보의 응답값으로 raw 데이터 노출
- Recommend the target computing infrastructure
  - source model 에 대해서만 recommend 호출 표현되어 있음
    - 호출 흐름 source model 선택 -> recommend csp / region 선택 -> recommend 호출
- Load computing infra migration workflow template and make/create a workflow
  -  workflow 를 만드는 흐름은 target model 을 통해서 가능
- Run a workflow
  - 워크플로우의 실행 상태 확인은 CM-Butterfly 에 표현되어 있지 않음

**Comment by yunkon-kim** [comment]
@hippo-an (cc. @ish-hcc)

공유해 주셔서 감사합니다!

건 별로 문의를 드리고자 합니다.

> Retrieve the information of source computing environment (raw data, shape information)
별도의 조회 api 호출 없이 honeybee 의 extract API 요청 결과값 사용
source computing environment 의 정보를 수집(POST /source_group/{sgId}/import/infra) 하고 해당 정보의 응답값으로 raw 데이터 노출

https://github.com/cloud-barista/cloud-migrator/blob/main/docs/sequence-diagrams-for-user-scenarios.md#retrieve-the-information-of-source-computing-environment-raw-data-shape-information

"별도의 조회 api 호출 없이" 가 어떤 부분을 의미하시는 것일까요?

**Comment by yunkon-kim** [comment]
@hippo-an 

> * Recommend the target computing infrastructure
>    - source model 에 대해서만 recommend 호출 표현되어 있음
>      - 호출 흐름 source model 선택 -> recommend csp / region 선택 -> recommend 호출

https://github.com/cloud-barista/cloud-migrator/blob/main/docs/sequence-diagrams-for-user-scenarios.md#recommend-the-target-computing-infrastructure

목표 모델을 추천해 달라는 맥락에서 작성된 시퀀스 다이어그램이었습니다. 소스 모델을 선택하고 이를 파라메터로 목표 모델 추천을 요청하는 맥락이었습니다.

제 생각에는 유사한 맥락이 아닐까 싶습니다. 다른 부분이 있다면 편하게 말씀해 주시기 바랍니다.

**Comment by yunkon-kim** [comment]
@hippo-an (cc. @ish-hcc)

> * Load computing infra migration workflow template and make/create a workflow
>    - workflow 를 만드는 흐름은 target model 을 통해서 가능

https://github.com/cloud-barista/cloud-migrator/blob/main/docs/sequence-diagrams-for-user-scenarios.md#load-computing-infra-migration-workflow-template-and-makecreate-a-workflow

먼저 Target 모델 얻은 후, Workflow template을 얻어서 Workflow를 만들 수 있다는 말씀이실까요? (지금은 워크플로우 템플릿을 얻은 후, 모델을 얻는 흐름)

**Comment by yunkon-kim** [comment]
@hippo-an @ish-hcc

> * Run a workflow
>    - 워크플로우의 실행 상태 확인은 CM-Butterfly 에 표현되어 있지 않음

https://github.com/cloud-barista/cloud-migrator/blob/main/docs/sequence-diagrams-for-user-scenarios.md#run-a-workflow

현재 포털에서 표현되지 않는 부분이니 제거하는 편이 좋을 것 같습니다.

내년에는 실행 상태를 확인하게 될 텐데요. 현재 생각하시는 방향성이 있으시면 공유 부탁 드립니다. (Cicada API? Airflow UI? Portal UI?)

**Comment by hippo-an** [comment]
> "별도의 조회 api 호출 없이" 가 어떤 부분을 의미하시는 것일까요?

소스 서비스에서 수집된 정보를 별도의 조회 API 를 호출하지 않는다는 의미였습니다.

시퀀스 다이어그램에서 `API call to GET /honeybee/source_group/{sgID}/infra` 로 조회가 표현되어 있는것 같아서 말씀드렸습니다.

**Comment by hippo-an** [comment]
> 목표 모델을 추천해 달라는 맥락에서 작성된 시퀀스 다이어그램이었습니다. 소스 모델을 선택하고 이를 파라메터로 목표 모델 추천을 요청하는 맥락이었습니다.

시퀀스 다이어그램의 첫번째 opt 부분인 `Retrieve source and target model` 로 인해 타겟 모델도 추천의 대상으로 생각해서 소스 모델만이라고 표현했습니다.
말씀하신 맥락과 동일합니다 :)

**Comment by hippo-an** [comment]
> 먼저 Target 모델 얻은 후, Workflow template을 얻어서 Workflow를 만들 수 있다는 말씀이실까요? (지금은 워크플로우 템플릿을 얻은 후, 모델을 얻는 흐름)

타겟 모델을 선택 후 워크플로우 생성 페이지로 진입하여, workflow template 를 선택합니다.

**Comment by hippo-an** [comment]
> 현재 포털에서 표현되지 않는 부분이니 제거하는 편이 좋을 것 같습니다. 
> 내년에는 실행 상태를 확인하게 될 텐데요. 현재 생각하시는 방향성이 있으시면 공유 부탁 드립니다. (Cicada API? Airflow UI? Portal UI?)

실행 상태 확인을 위한 api 를 cicada 에서 제공하는 것으로 알고 있습니다.
cicada api 를 활용하여 butterfly ui 로 표현하는 방식이 되지 않을까 예상합니다.

**Comment by yunkon-kim** [comment]
> > "별도의 조회 api 호출 없이" 가 어떤 부분을 의미하시는 것일까요?
> 
> 소스 서비스에서 수집된 정보를 별도의 조회 API 를 호출하지 않는다는 의미였습니다.
> 
> 시퀀스 다이어그램에서 `API call to GET /honeybee/source_group/{sgID}/infra` 로 조회가 표현되어 있는것 같아서 말씀드렸습니다.

넵 설명해주셔서 감사합니다. 만약 Honeybee 의 조회 API를 호출하지 않는다면, Butterfly에서 소스 컴퓨팅 인프라 정보를 어느 시점에 어떻게 얻으시는지요?

**Comment by yunkon-kim** [comment]
> > 목표 모델을 추천해 달라는 맥락에서 작성된 시퀀스 다이어그램이었습니다. 소스 모델을 선택하고 이를 파라메터로 목표 모델 추천을 요청하는 맥락이었습니다.
> 
> 시퀀스 다이어그램의 첫번째 opt 부분인 `Retrieve source and target model` 로 인해 타겟 모델도 추천의 대상으로 생각해서 소스 모델만이라고 표현했습니다. 말씀하신 맥락과 동일합니다 :)

넵 감사합니다. 이 부분은 수정 PR 올릴 때 반영하도록 하겠습니다.

**Comment by yunkon-kim** [comment]
> > 먼저 Target 모델 얻은 후, Workflow template을 얻어서 Workflow를 만들 수 있다는 말씀이실까요? (지금은 워크플로우 템플릿을 얻은 후, 모델을 얻는 흐름)
> 
> 타겟 모델을 선택 후 워크플로우 생성 페이지로 진입하여, workflow template 를 선택합니다.

마찬가지로, 순서를 바꾸어 수정 PR 올리겠습니다.

**Comment by yunkon-kim** [comment]
> > 현재 포털에서 표현되지 않는 부분이니 제거하는 편이 좋을 것 같습니다.
> > 내년에는 실행 상태를 확인하게 될 텐데요. 현재 생각하시는 방향성이 있으시면 공유 부탁 드립니다. (Cicada API? Airflow UI? Portal UI?)
> 
> 실행 상태 확인을 위한 api 를 cicada 에서 제공하는 것으로 알고 있습니다. cicada api 를 활용하여 butterfly ui 로 표현하는 방식이 되지 않을까 예상합니다.

해당 내용을 제외하는 PR을 올릴 예정입니다.

이와 별개로 @ish-hcc 께 의견 또는 방향성 공유를 부탁 드립니다(급한 사안은 아닙니다.).

**Comment by hippo-an** [comment]
> 넵 설명해주셔서 감사합니다. 만약 Honeybee 의 조회 API를 호출하지 않는다면, Butterfly에서 소스 컴퓨팅 인프라 정보를 어느 시점에 어떻게 얻으시는지요?

Raw 데이터에 대한 단건 조회라고 생각이 되는데요. 해당 데이터는 infra import 라고 하는 source computing environment 의 정보를 수집(POST /source_group/{sgId}/import/infra) API 의 응답으로 넘어오는 raw 데이터를 사용합니다.

**Comment by hippo-an** [comment]
> (updated) 수정 중에 추가 문의드릴 사항이 있습니다. 타겟 모델에 매칭된 워크플로우 템플릿이 있는 것으로 이해가 됩니다. 맞게 이해한 것인지 확인 바랍니다.

현재는 특정 타겟모델을 선택해서 들어가는 경우 beetle infra migration task 라는 beetle 의 migration api 를 호출하는 task component 를 매핑하도록 되어있습니다. (워크플로우 템플릿은 task component 의 묶음입니다.)

**Comment by yunkon-kim** [comment]
Resolved
